[build]
  command = "pnpm install && NODE_OPTIONS='--max-old-space-size=4096' pnpm run build"
  publish = "build/client"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
